import { env } from "cloudflare:workers";

const allowedSections = new Set(["overview", "demand", "architecture", "location", "economics", "risk-delivery", "scenario-lab"]);

export async function POST(request: Request) {
  let payload: { message?: unknown; context?: { section?: unknown; scenarioInputs?: unknown } };
  try { payload = await request.json(); } catch { return Response.json({ error: "Invalid request." }, { status: 400 }); }
  const message = typeof payload.message === "string" ? payload.message.trim() : "";
  if (!message || message.length > 4000) return Response.json({ error: "Enter a question under 4,000 characters." }, { status: 400 });

  const apiKey = env.OPENAI_API_KEY;
  const model = env.OPENAI_MODEL;
  if (!apiKey || !model) return Response.json({ error: "AI Research Assistant is awaiting secure server configuration." }, { status: 503 });

  const section = typeof payload.context?.section === "string" && allowedSections.has(payload.context.section) ? payload.context.section : "overview";
  // TODO: Replace this client-provided draft context with server-validated research records and saved scenario inputs.
  const draftInputs = payload.context?.scenarioInputs && typeof payload.context.scenarioInputs === "object" ? JSON.stringify(payload.context.scenarioInputs).slice(0, 2000) : "none";
  const instructions = "You assist an investment committee reviewing a proposed university consortium AI data center. The 25 MW figure is a confirmed definition of an expandable total-facility design envelope, not IT load, a validated demand forecast, utility commitment or approval to build. The current preferred 2030 planning case is an illustrative B200/H200/L40S mix with 63.3% of original reference work assigned to high-end classes and 36.7% to L40S-class, under assumed throughput factors. L40S uses GDDR6, not HBM. Five hypothetical members sum to 3.5 MIT reference demand units under unmeasured weights. The 2030 base facility estimate is 13.204 MW; a first-phase inquiry is roughly 10–14 MW. The 2035 base is 19.795 MW and high case 39.571 MW. The older approximately 14.05 MW all-high-end case is a historical stress comparison, not the current planning base. Each modeled GPU-hour belongs to one primary compute task; biomedical and robotics labels are nonadditive, and coding agents are an inference subtype with assumed incremental requests. The preferred delivery path to test is a consortium-controlled colo core with eligible cloud burst, compared against all-cloud and other options. Illustrative 2027–2036 cost NPVs are public-anchor all-cloud $1.152bn, 70% colo core plus cloud $1.177bn, full colo $1.176bn, full own $1.219bn, full dedicated $1.452bn, 70% dedicated plus cloud $1.389bn, and 70% own plus cloud $1.214bn. These are model outputs, not vendor quotes or purchase authority. Public price anchors are Lambda B200 $8.87 per GPU-hour for a 256+ GPU networked cluster and Runpod H200 multi-node $4.31 and L40S Secure Cloud $1.09 per GPU-hour; they are cross-product reference points, not comparable bids or one-supplier availability. Dedicated reservation rates $6.65/$3.45/$0.90 per B200/H200/L40S GPU-hour are unquoted assumptions. Texas/ERCOT, Iowa/MISO, Central Ohio/AEP-PJM and Virginia/Dominion-PJM form an unranked US inquiry pool. No parcel has verified staged power, energization, fiber, cooling, permit or tariff terms. Robot and instrument closed-loop control and data lacking transfer permission stay at the device or origin. Restricted work may enter a consortium-controlled owned or contractually dedicated secure environment only after project-specific dataset, institutional, user, isolation, audit and agreement review. Ownership alone grants no data rights. Begin reversible compute service, demand telemetry, security governance and parcel diligence, while deferring full 25 MW approval. A 2030 first-phase opening is a conditional model date, not promised delivery. Never invent research data, city rankings, workload measurements, contract terms, data permissions or approvals. Say TBD when evidence is unavailable. Distinguish user-entered scenario assumptions, model outputs and sourced findings. Treat client-provided scenario context as unverified until validated against server-side records.";
  try {
    const upstream = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model, store: false, instructions, input: `Current section: ${section}\nUnverified draft scenario inputs: ${draftInputs}\nQuestion: ${message}` }) });
    if (!upstream.ok) return Response.json({ error: "AI service is temporarily unavailable." }, { status: 502 });
    const data = await upstream.json() as { output?: Array<{ content?: Array<{ type?: string; text?: string }> }> };
    const reply = data.output?.flatMap(item => item.content || []).filter(item => item.type === "output_text").map(item => item.text || "").join("\n").trim();
    return Response.json({ reply: reply || "No answer was returned." });
  } catch { return Response.json({ error: "AI service is temporarily unavailable." }, { status: 502 }); }
}
